name: Oracle ARM Hunter

on:
  workflow_dispatch: # Qo'lda ishga tushirish tugmasini chiqaradi
  schedule:
    - cron: '*/5 * * * *' # Har 5 daqiqada avtomatik ishga tushadi

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3' # Eng yangi barqaror PHP talqinini ishlatamiz

      - name: Install Dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Run Instance Hunter
        run: php index.php
        env:
          # GitHub Secrets-dan ma'lumotlarni o'qiymiz
          OCI_REGION: ${{ secrets.OCI_REGION }}
          OCI_USER_ID: ${{ secrets.OCI_USER_ID }}
          OCI_TENANCY_ID: ${{ secrets.OCI_TENANCY_ID }}
          OCI_KEY_FINGERPRINT: ${{ secrets.OCI_FINGERPRINT }}
          OCI_PRIVATE_KEY: ${{ secrets.OCI_KEY_FILE }}
          OCI_SUBNET_ID: ${{ secrets.OCI_SUBNET_ID }}
          OCI_IMAGE_ID: ${{ secrets.OCI_IMAGE_ID }}
          
          # Server parametrlari (24GB RAM va 4 OCPU)
          OCI_OCPUS: 4
          OCI_MEMORY_IN_GBS: 24
          OCI_SHAPE: "VM.Standard.A1.Flex"
          
          # Telegram bildirishnomalari
          TELEGRAM_BOT_API_KEY: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_USER_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          
          # Singapur uchun odatiy AD (agar xato bersa, o'zingiznikini qo'shing)
          OCI_AVAILABILITY_DOMAIN: "USvN:AP-SINGAPORE-1-AD-1"
